version: 2
jobs:
  deploy:
    working_directory: ~/poker-bo
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: ls
          command: ls
      - run:
          name: Deploy Over SCP
          command: |
            scp -r ./* "$SSH_USER@$SSH_HOST:$SSH_DEPLOY_PATH"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy